# Generated by Django 4.1 on 2022-08-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='rating',
            field=models.FloatField(default=3, null=True),
        ),
    ]
