# Generated by Django 4.1 on 2022-08-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('processor', models.CharField(max_length=120)),
                ('screen_size', models.IntegerField()),
                ('cpu', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=60)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
