# Generated by Django 4.1 on 2022-08-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptops',
            name='processor',
        ),
    ]
