# Generated by Django 4.1 on 2022-08-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapi', '0002_remove_laptops_processor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptops',
            old_name='storage',
            new_name='ram',
        ),
    ]
