# Generated by Django 4.1 on 2022-08-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapi', '0003_rename_storage_laptops_ram'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptops',
            name='rating',
            field=models.FloatField(default=3, null=True),
        ),
    ]
