# Generated by Django 4.1 on 2022-08-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopapi', '0004_laptops_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptops',
            old_name='rating',
            new_name='ratings',
        ),
    ]
